/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author yorbarbe
 */
public class frmClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuarios
     */
    public frmClientes() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetroCustom1 = new RSMaterialComponent.RSTableMetroCustom();
        rSTextFieldMaterial1 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel1 = new javax.swing.JLabel();
        rSTextFieldMaterial2 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial3 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial4 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial5 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial6 = new RSMaterialComponent.RSTextFieldMaterial();
        rSTextFieldMaterial7 = new RSMaterialComponent.RSTextFieldMaterial();
        rSComboBoxMaterial1 = new RSMaterialComponent.RSComboBoxMaterial();
        rSTextFieldMaterial8 = new RSMaterialComponent.RSTextFieldMaterial();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuBuscar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmenuacerca = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setTitle("Clientes");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1000, 650));

        rSTableMetroCustom1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rSTableMetroCustom1.setBackgoundHead(new java.awt.Color(255, 102, 0));
        rSTableMetroCustom1.setBackgoundHover(new java.awt.Color(255, 102, 0));
        rSTableMetroCustom1.setColorPrimaryText(new java.awt.Color(255, 102, 0));
        rSTableMetroCustom1.setColorSecundaryText(new java.awt.Color(255, 102, 0));
        rSTableMetroCustom1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rSTableMetroCustom1.setFontHead(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        rSTableMetroCustom1.setFontRowHover(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rSTableMetroCustom1.setFontRowSelect(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rSTableMetroCustom1.setSelectionBackground(new java.awt.Color(255, 102, 0));
        jScrollPane1.setViewportView(rSTableMetroCustom1);

        rSTextFieldMaterial1.setForeground(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial1.setToolTipText("");
        rSTextFieldMaterial1.setColorMaterial(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rSTextFieldMaterial1.setPhColor(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial1.setPlaceholder("Numero de Documento");
        rSTextFieldMaterial1.setSelectionColor(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Documento");

        rSTextFieldMaterial2.setForeground(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial2.setToolTipText("");
        rSTextFieldMaterial2.setColorMaterial(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rSTextFieldMaterial2.setPhColor(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial2.setPlaceholder("Nombres");
        rSTextFieldMaterial2.setSelectionColor(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial2ActionPerformed(evt);
            }
        });

        rSTextFieldMaterial3.setForeground(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial3.setToolTipText("");
        rSTextFieldMaterial3.setColorMaterial(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rSTextFieldMaterial3.setPhColor(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial3.setPlaceholder("Correo");
        rSTextFieldMaterial3.setSelectionColor(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial3ActionPerformed(evt);
            }
        });

        rSTextFieldMaterial4.setForeground(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial4.setToolTipText("");
        rSTextFieldMaterial4.setColorMaterial(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rSTextFieldMaterial4.setPhColor(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial4.setPlaceholder("Apellidos");
        rSTextFieldMaterial4.setSelectionColor(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial4ActionPerformed(evt);
            }
        });

        rSTextFieldMaterial5.setForeground(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial5.setToolTipText("");
        rSTextFieldMaterial5.setColorMaterial(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rSTextFieldMaterial5.setPhColor(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial5.setPlaceholder("Tipo");
        rSTextFieldMaterial5.setSelectionColor(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial5ActionPerformed(evt);
            }
        });

        rSTextFieldMaterial6.setForeground(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial6.setToolTipText("");
        rSTextFieldMaterial6.setColorMaterial(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rSTextFieldMaterial6.setPhColor(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial6.setPlaceholder("Dirección");
        rSTextFieldMaterial6.setSelectionColor(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial6ActionPerformed(evt);
            }
        });

        rSTextFieldMaterial7.setForeground(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial7.setToolTipText("");
        rSTextFieldMaterial7.setColorMaterial(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rSTextFieldMaterial7.setPhColor(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial7.setPlaceholder("Ciudad");
        rSTextFieldMaterial7.setSelectionColor(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial7ActionPerformed(evt);
            }
        });

        rSComboBoxMaterial1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo de Documento", "CEDULA DE CIUDADANIA", "TARJETA DE IDENTIDAD", "CEDULA DE EXTRANJERIA", "PASAPORTE", "NIT" }));
        rSComboBoxMaterial1.setColorMaterial(new java.awt.Color(255, 102, 0));
        rSComboBoxMaterial1.setDoubleBuffered(true);
        rSComboBoxMaterial1.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N

        rSTextFieldMaterial8.setForeground(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial8.setToolTipText("");
        rSTextFieldMaterial8.setColorMaterial(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rSTextFieldMaterial8.setPhColor(new java.awt.Color(0, 0, 0));
        rSTextFieldMaterial8.setPlaceholder("Telefono");
        rSTextFieldMaterial8.setSelectionColor(new java.awt.Color(255, 102, 0));
        rSTextFieldMaterial8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterial8ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OBSERVACION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10), new java.awt.Color(255, 102, 0))); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jMenu1.setText("Menu");

        jMenuNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Clientes/clientes.png"))); // NOI18N
        jMenuNuevo.setText("Nuevo");
        jMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNuevo);
        jMenu1.add(jSeparator1);

        jMenuBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar.png"))); // NOI18N
        jMenuBuscar.setText("Buscar");
        jMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuBuscar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        jMenu3.add(jSeparator2);

        jmenuacerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/info.png"))); // NOI18N
        jmenuacerca.setText("Manual");
        jmenuacerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuacercaActionPerformed(evt);
            }
        });
        jMenu3.add(jmenuacerca);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rSTextFieldMaterial4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSTextFieldMaterial8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSTextFieldMaterial6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rSComboBoxMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSTextFieldMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSTextFieldMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSTextFieldMaterial7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(rSTextFieldMaterial3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSTextFieldMaterial5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSTextFieldMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSTextFieldMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(rSComboBoxMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSTextFieldMaterial4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSTextFieldMaterial6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSTextFieldMaterial8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSTextFieldMaterial7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTextFieldMaterial3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSTextFieldMaterial5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoActionPerformed
       
    }//GEN-LAST:event_jMenuNuevoActionPerformed

    private void jMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarActionPerformed
        
    }//GEN-LAST:event_jMenuBuscarActionPerformed

    private void jmenuacercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuacercaActionPerformed
        frmAcerca abrir = new frmAcerca();
        abrir.setVisible(true);
    }//GEN-LAST:event_jmenuacercaActionPerformed

    private void rSTextFieldMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial1ActionPerformed

    private void rSTextFieldMaterial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial2ActionPerformed

    private void rSTextFieldMaterial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial3ActionPerformed

    private void rSTextFieldMaterial4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial4ActionPerformed

    private void rSTextFieldMaterial5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial5ActionPerformed

    private void rSTextFieldMaterial6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial6ActionPerformed

    private void rSTextFieldMaterial7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial7ActionPerformed

    private void rSTextFieldMaterial8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterial8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTextFieldMaterial8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBuscar;
    private javax.swing.JMenuItem jMenuNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem jmenuacerca;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial1;
    private RSMaterialComponent.RSTableMetroCustom rSTableMetroCustom1;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial1;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial2;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial3;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial4;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial5;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial6;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial7;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial8;
    // End of variables declaration//GEN-END:variables
}
